### PR TITLE
_readableState is private, use byteCount

### LINKED ISSUE #1: Only first 65 397 bytes get uploaded
Hi! I am trying to upload an `image/jpeg` file into my Azure container. My file is 286 025 bytes large, but only first 65 397 bytes get uploaded - after that, the adapter fires my callback and reports a successful operation.

Interesting to note is that the uploaded file is consistently truncated to 65 397 bytes even after multiple attempts.

Here is a short code that I use:

``` js
return new Promise(function upload (resolve, reject) {
  // Upload! blobStore contains skipper-azure as adapter and all necessary keys and secrets
  req.file('photo').upload(sails.config.connections.blobStore, function (err, files) {
    // Error occured?
    if (err)
      return reject(err)

    // Did we upload anything?
    if (! files.length)
      err = new Error('No files uploaded!')

    return resolve(files[0])    // We only upload one at a time
  })
})
```

And I upload my file with `curl`:

`curl -X POST -F "photo=@/path/to/test.jpg" http://localhost:000/contacts/1/photo`

After that, Sails sends me the expected response and closes the connection normally. Could this be a bug in the module...?

Thanks for any guidance in this matter!

### PR DESCRIPTION
**Pull request by robertrossmann**
Fixes #1

### CODE REVIEW

**Comment by lukasredev** [comment]
It's strange: If I use the module in my own project byteCount is  working fine, but when running the sails-adapter-tests byteCount seems to be undefined. This was the reason why I changed it to _readableState.length, because it seems to be always working ...

**Comment by robertrossmann** [comment]
I could try having a look at those tests... I suspect that the `_readableState` only represents the part of the upload that is immediately available for processing, which may or may not be the whole dataset.

Further reading at [IO.js](https://github.com/iojs/io.js/issues/445) (should apply to Node.js, too).

**Comment by robertrossmann** [comment]
The `byteCount` property comes from [multiparty](https://github.com/andrewrk/node-multiparty/#part-part), the body parser that Skipper uses internally. It is then quite likely that the property is not set when doing some test mockups.

On a side note, I wonder why Azure requires explicit content-length... None of the other "big guys", S3, GridFS, or Google Cloud Storage adapters need to provide this. Could there perhaps be a different way of uploading files to Azure without having to know the content-length in advance?

**Comment by lukasredev** [comment]
Ok thanks for the information.
Yes this seemed kind of weird to me either. Maybe you could open an issue or write someone on the azure-storage project?

**Pull request closed without merging**
